apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-demo-database-deployment
  namespace: java-demo

  labels:
    app: java-demo-database
    role: database
    stage: local

spec:
  selector:
    matchLabels:
      app: java-demo-database
  template:
    metadata:
      labels:
        app: java-demo-database
    spec:
      serviceAccountName: default # d. if you wanna set specific RBAC to the pod
      containers:
        - name: java-demo-database
          image: mysql:latest
          imagePullPolicy: IfNotPresent # d. Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "database"
            - name: MYSQL_USER
              value: "jonathan"
            - name: MYSQL_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
            
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
      
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc