apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-demo-backend-deployment
  namespace: local

  labels:
    app: java-demo-backend
    role: backend
    stage: local

spec:
  selector:
    matchLabels:
      app: java-demo-backend
      role: backend
      stage: local

  strategy:
    type: Recreate # d. RollingUpdate
  template:
    metadata:
      labels:
        app: java-demo-backend
        role: backend
        stage: local

    spec:
      restartPolicy: Always # d.
      containers:
        - name: java-demo-backend
          image: jojoooo1/carros
          imagePullPolicy: Never # d. Always
          # env:
          #   - name: JAVA_TOOL_OPTIONS # used by distroless image
          #     value:
          ports:
            - containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     port: 8080
          #     path: /actuator/info
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     port: service-port
          #     path: /actuator/health
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 5
          # Sets in jib: -Xms512m, -Xmx1024m (becarefull with the compatibility)
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "1000"
      