spring:
  # Could not disable h2 console il boostrap.yaml that is why I created application-dev
  h2:
    console:
      enabled: true
  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:mem:database # URL in console to set
  #   username: sa # default username
  #   password:
  datasource:
    url: jdbc:mysql://localhost:3306/database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: jonathan
    password: password