spring:
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        ddl-auto: create-drop
        
logging:
  level:
    root: info
    org:
      springframework: info
      hibernate: error
      