management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

spring:
  cloud:
    kubernetes:
      reload:
        enabled: true
      config:
      #   # ConfigMap default
        name: carros
        namespace: java-demo
        sources:
            - name: config-test # Not working: issue opened
              namespace: java-demo
