apiVersion: v1
kind: Service
metadata:
  name: mysql-test-service # dns
  namespace: default
  labels:
    app: java-demo-backend
    role: database
    stage: local

spec:
  selector:
    app: mysql-test
  ports:
    - protocol: TCP # d.
      # Port exposed by the service
      port: 3306
      # Port of the pod accessed
      targetPort: 3306
