apiVersion: v1
kind: ConfigMap

metadata:
  name: carros
  namespace: default

data:
  bootstrap.yml: |-
    # MySQL
    spring:
      datasource:
        url: jdbc:mysql://mysql-test-service:3306/database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: jonathan
        password: password

      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL55Dialect
            show_sql: true
            format_sql: true
        hibernate:
          ddl-auto: create
      #Security
      security:
        user:
          name: admin
          password: password
          
    logging:
      level:
        root: info
        org:
          springframework: info
          hibernate: info
