---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # is cluster scoped
# kind: Role # is namespace scoped
metadata:
  name: read-namespace-cluster-role
  # namespace: # only use with Role since it is namespace scoped

rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-namespace
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: read-namespace-rolebinding
  namespace: default

# Target
subjects:
  - kind: ServiceAccount
    name: read-namespace
    namespace: default

# Role reference => Created in folder rbac
roleRef:
  kind: ClusterRole
  name: read-namespace-cluster-role
  apiGroup: rbac.authorization.k8s.io
