spring:
  profiles:
    active: '@myActiveProfile@'
  jpa:
    properties:
      hibernate:
        #  Hibernate uses "dialect" configuration to know which database you are using
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
        ddl-auto: none
        # show_sql=false
        # format_sql=false

logging:
  level:
    root: warn
    org:
      springframework:
        web: INFO
      hibernate: ERROR
