apiVersion: v1
kind: ConfigMap

metadata:
  name: carros
  namespace: java-demo

data:
  application.yml: |-
    # MySQL
    spring:

      datasource:
        url: jdbc:mysql://java-demo-database-service:3306/database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: jonathan
        password: password

      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL55Dialect
            show_sql: true
            format_sql: true

      liquibase:
        change-log: classpath:/db/db.changelog-master.xml
    #               
    logging:
      config: conf/log4j2-dev.xml
