apiVersion: apps/v1
kind: Deployment

metadata:
  name: java-demo-backend-deployment
  namespace: local

  labels:
    app: java-demo-backend
    role: backend
    stage: local

spec:
  selector:
    matchLabels:
      app: java-demo-backend
      role: backend
      stage: local

  strategy:
    type: Recreate # d. RollingUpdate
  template:
    metadata:
      labels:
        app: java-demo-backend
        role: backend
        stage: local

    spec:
      restartPolicy: Always # d.
      containers:
        - name: java-demo-backend
          image: jojoooo1/carros
          imagePullPolicy: Never # d. Always
          # env:
          #   - name: JAVA_TOOL_OPTIONS # used by distroless image
          #     value:
          ports:
            - containerPort: 8080
          #
          # Liveness and Readiness
          # To use when restarting the app will recover it (heap, stack problems etc.)
          # livenessProbe:
          #   initialDelaySeconds: 60
          #   httpGet:
          #     port: 8080
          #     path: /alive
          readinessProbe:
            periodSeconds: 10 # d.
            failureThreshold: 1 # d.
            httpGet:
              port: 8080
              path: /actuator/health
          # 
          # RESOURCES (Sets in jib: -Xms512m, -Xmx1024m (becarefull with the compatibility))
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1024Mi"
              cpu: "1"
