name: CI for building and deploying release candidate image to staging

on:
  push:
    branches: [release-*] # d. (opened, synchronize, or reopened)

env:
  GITHUB_USERNAME: jojoooo1
  DOCKER_USERNAME: jojoooo1
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: carros

jobs:
  release-build-and-deploy:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      ## Setup ## 
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      ## Unit & Integration Test ##
      - name: Run Unit & Integration Test
        run: mvn clean verify -P all-test

      # TODO: on push failure send notification
      # Can use Sonar
      # Or can use PMD, FindBugs and Checkstyle
      # Can add dependency scanning

      ## Sets environment variables ##
      - name: "Sets ENV_VARIABLE"
        run: |
          echo "::set-env name=SOURCE_BRANCH::${GITHUB_REF##*/}"
          echo "::set-env name=RELEASE_VERSION::${GITHUB_REF##*release-}"
          echo "::set-env name=IMAGE_REGISTRY::docker.io/${DOCKER_USERNAME}/$DOCKER_IMAGE"

      - run: echo "::set-env name=RELEASE_NAME::${RELEASE_VERSION}.RC-$GITHUB_SHA" # new run because can not use $RELEASE_VERSION in same run
      - name: "echo ENV_VARIABLE"
        run: |
          echo SOURCE_BRANCH: "$SOURCE_BRANCH"
          echo RELEASE_VERSION: "$RELEASE_VERSION"
          echo RELEASE_NAME: "$RELEASE_NAME"
          echo IMAGE_REGISTRY: $IMAGE_REGISTRY
          echo DOCKER_USERNAME: $DOCKER_USERNAME

      ## Sets Maven version ##
      - name: Sets Maven Release Candidate version in pom.xml
        run: mvn versions:set -DnewVersion=$RELEASE_NAME

      ## Push to image registry ##
      - name: Build & Push Release Candidate to Docker registry
        run: |
          mvn clean compile -P staging jib:build \
            -Djib.to.auth.username=$DOCKER_USERNAME \
            -Djib.to.auth.password=$DOCKER_PASSWORD \
            -Djib.to.image=$IMAGE_REGISTRY \
            -Djib.to.tags=$RELEASE_NAME

      ## Commit maven version update ##
      - name: Commit changes to $SOURCE_BRANCH
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
          git diff
          git commit -am "Pushed image to: docker.io/${DOCKER_USERNAME}/${DOCKER_IMAGE}:$RELEASE_NAME"
          git push origin $SOURCE_BRANCH
