name: CI for building and deploying image from release branch

on:
  pull_request:
    types: [opened, synchronize, reopened, closed] # closed
    branches: [master]

env:
  GITHUB_USERNAME: jojoooo1
  DOCKER_USERNAME: jojoooo1
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: carros

jobs:
  # Does not deloy to k8s staging => GitOps pattern (flux will do it automatically)
  build-and-deploy-hotfix-candidate:
    if: "contains(toJSON(github.head_ref), 'hotfix-') && github.event.action != 'closed' && ! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      ## Setup ## 
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      ## Unit & Integration Test ##
      - name: Run Unit & Integration Test
        run: mvn clean verify -P all-test

      # TODO: on push failure send notification
      # Can use Sonar
      # Or can use PMD, FindBugs and Checkstyle
      # Can add dependency scanning
      # Can upload test report

      # TODO: bump release version



      