name: CI for building and deploying stable image to master

on:
  # Only push become we want it to be triggered when the merge happen
  push:
    branches: [master]

# TODO: Finish release on master
# TODO: Hotfix workflow
jobs:
  feature-build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # - name: Cache Maven packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2

      # # Test
      # - name: Build with Maven
      #   run: mvn clean verify -P all-test # can use sonar:sonar

