name: "Test, build and deploy master image"

on:
  pull_request:
    types: [closed] # closed
    branches: [master]

env:
  GITHUB_USERNAME: jojoooo1
  DOCKER_USERNAME: jojoooo1
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE: carros

jobs:
  # Does not deloy to k8s master => GitOps pattern (flux will do it automatically)
  test-build-deploy-master:
    # From release: on pull_request closed and merged to master
    if: "contains(toJSON(github.head_ref), 'release-') || contains(toJSON(github.head_ref), 'hotfix-')"
    runs-on: ubuntu-latest
    steps:
      ## Setup ## 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      ## Sets environment variables ##
      - name: "Sets ENV_VARIABLE for release branch"
        if: "contains(toJSON(github.head_ref), 'release-')"
        run: |
          RELEASE_VERSION=${GITHUB_HEAD_REF##*release-}"
          TAG_LIST=(`echo $RELEASE_VERSION | tr '.' ' '`)
          
          # Github bug one line if not working: [[ "${#TAG_LIST[@]}" -ne 3 ]] && echo "$RELEASE_VERSION is not a valid semantic version" && exit 1
          # Exit if invalid semver
          if [[ ${#TAG_LIST[@]} -ne 3 ]]; then
            echo "$RELEASE_VERSION is not a valid semantic version"
            exit 1
          fi
          
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
          echo "::set-env name=IMAGE_REGISTRY::docker.io/${DOCKER_USERNAME}/$DOCKER_IMAGE"
      
      - name: "Sets ENV_VARIABLE for hotfix branch"
        if: "contains(toJSON(github.head_ref), 'hotfix-')"
        run: |
          git fetch --prune --tags # fetch all tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          TAG_LIST=(`echo $LATEST_TAG | tr '.' ' '`)

          # Github bug one line if not working: [[ "${#TAG_LIST[@]}" -ne 3 ]] && echo "$LATEST_TAG is not a valid semantic version" && exit 1
          # Exit if invalid semver
          if [[ ${#TAG_LIST[@]} -ne 3 ]]; then
            echo "$LATEST_TAG is not a valid semantic version"
            exit 1
          fi
          
          V_MAJOR=${TAG_LIST[0]}
          V_MINOR=${TAG_LIST[1]}
          V_PATCH=$(( ${TAG_LIST[2]} + 1))
          
          echo "::set-env name=RELEASE_VERSION::${V_MAJOR}.${V_MINOR}.${V_PATCH}"
          echo "::set-env name=IMAGE_REGISTRY::docker.io/${DOCKER_USERNAME}/$DOCKER_IMAGE"

      - name: "Sets RELEASE_NAME"
        run: echo "::set-env name=RELEASE_NAME::${RELEASE_VERSION}" # new run because can not use $RELEASE_VERSION in same run
      
      - name: "echo ENV_VARIABLE"
        run: |
          echo BRANCH_NAME: "$GITHUB_HEAD_REF"
          echo RELEASE_VERSION: "$RELEASE_VERSION"

          echo RELEASE_NAME: "$RELEASE_NAME"
          echo IMAGE_REGISTRY: $IMAGE_REGISTRY
          echo DOCKER_USERNAME: $DOCKER_USERNAME

      ## Sets Maven version ##
      - name: Sets Maven Master Image version in pom.xml
        run: mvn versions:set -DnewVersion=$RELEASE_NAME

      ## Push to image registry ##
      - name: Build & Push Master Image to Docker registry
        run: |
          mvn clean compile -P k8s jib:build \
            -Djib.to.auth.username=$DOCKER_USERNAME \
            -Djib.to.auth.password=$DOCKER_PASSWORD \
            -Djib.to.image=$IMAGE_REGISTRY \
            -Djib.to.tags=$RELEASE_NAME

      ## Can add Static Analysis of vulnerabilities for Containers (clair)

      ## Commit maven version update ##
      ## If protected can use force push with admin right and skip-ci
      - name: "Commit changes to 'master'"
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
          
          # Sync with remote repo to checkout master
          git fetch
          git checkout master

          git add .
          git commit -m "version updated to '$RELEASE_NAME' in pom.xml"
          git push origin master
          SHA_REF=$(git rev-parse HEAD)

          # Sets status check to success in order to be able to merge after last commit
          curl -X POST -H "Authorization: token ${{ secrets.CREATE_STATUS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
            --data '{"state": "success", "context": "test-build-deploy-master", "description": "Test, build and deploy master image", "target_url": '"\"https://github.com/Jojoooo1/spring-boot-using-gitflow/actions/runs/${GITHUB_RUN_ID}\"}" \
            "https://api.github.com/repos/Jojoooo1/spring-boot-using-gitflow/statuses/$SHA_REF"

      - name: Create & push tag
        run: |
          git tag -a $RELEASE_VERSION -m "release: $RELEASE_VERSION"
          git push origin $RELEASE_VERSION
