# only used for testing purpose

apiVersion: skaffold/v2beta1
kind: Config

profiles:
  ### Local environment ###
  - name: minikube
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube

    build:
      local:
        push: false # will not push the image
      artifacts:
        - image: jojoooo1/carros # name of the image that will be build locally
          # context: . # context where the image is being built
          jib:
            args:
              - -P k8s #
            type: maven
      tagPolicy:
        gitCommit: {} # first look at tag, then use short commit
    # test: Container Structure Tests
    deploy:
      statusCheckDeadlineSeconds: 120 # d. 120s
      kubeContext: minikube
      kubectl: # deploy using kubectl
        manifests:
          # - "manifest/database/*.yaml"
          - "./skaffold/manifest/*.yaml"
          
    # Sets by default already
    # portForward:
    #   - resourceType: Service
    #     resourceName: spring-app-backend-service
    #     namespace: default
    #     port: 8080
    #     localPort: 8080

    #   - resourceType: Service
    #     resourceName: spring-app-database-service
    #     namespace: default
    #     port: 3306
    #     localPort: 3306